[package]
name = "bevy-demos"
version = "0.1.0"
authors = ["ilya"]
edition = "2018"

[profile.dev]
opt-level = 3               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.
debug = 0

[dependencies]
rand = "0.8.2"
bevy = "0.4.0"